environment:
  matrix:
  - nodejs_version: "8.0"
  - nodejs_version: "9.0"

platform:
  - x64
  - x86

configuration: Release

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm config set python python2.7
  - npm config set msvs_version 2015
  - npm install --ignore-scripts

build_script:
  - npm run configure
  - npm run build

test_script:
  - node --version
  - npm --version
  - npm test

version: 1.0.{build}