environment:
  matrix:
  - nodejs_version: "8.0"
    electron_version: "1.8.3"

platform:
  - x64
  - x86

configuration: Release
build: off

install:
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - npm --version
  - npm config set python python2.7
  - npm config set msvs_version 2015

  # build for nodejs
  - npm install --build-from-source

  # build for electron
  - npm install --build-from-source --runtime=electron --target=%ELECTRON_VERSION% --dist-url=https://atom.io/download/atom-shell

  # package
  - IF %APPVEYOR_REPO_TAG%==true npm run package --verbose
  - IF %APPVEYOR_REPO_TAG%==true npm run package --runtime=electron --target=%ELECTRON_VERSION% --verbose

test_script:
  - npm test

artifacts:
  - path: build\stage\$(package_version)\*.tar.gz
    name: myartifact

deploy:
  provider: GitHub
  auth_token:
    secure: aJwZ9iQ92v6hv7jV/cs4e2LCpMuhSevGlrdrEKN+WqWES4a7rIcXnK1FpmdhLcjn
  tag: $(package_version)
  artifact: myartifact
  on:
    appveyor_repo_tag: true